### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by swtnikita50** [leakec/tfc#17]
### Describe the bug:
I am trying to build this library from source for a Windows PC.
Following the instructions from the Build From Source Section, I installed all the system dependencies and package dependencies. While running the command:

### Reproducing code example:
```python setup.py bdist_wheel```

### Error message:
I am getting this error:
```cl : Command line error D8021 : invalid numeric argument '/Wextra'```

### System / TFC version information:
 - OS: Windows11
 - Python Version: 3.9.15
 - TFC Version: 1.0.2

### Additional Comments
Seems to be an issue in the setup.py file but I can't be sure as I don't know much about CMake.

**Comment by leakec** [comment]
Unfortunately, we do not support native builds on Windows, even from source. The reason for this is one of our dependencies, `jaxlib`, does not support native Windows builds. Therefore, even if you could build `tfc` natively on Windows, you wouldn't be able to use much of it, since its dependencies would not be satisfied.

However, you can definitely build this on Windows Subsystem for Linux (WSL). There you should be able to install the binary releases directly from `pip`, i.e., `pip install tfc`, or you can build from source if you so desire.

If in the future `jaxlib` starts releasing binary wheels for Windows, we will do the same. In the meantime, `WSL` is the only option on Windows.

**Comment by leakec** [comment]
@swtnikita50 We now support native Windows builds, as `jaxlib` started publishing Windows binary wheels. As of `tfc-v1.0.7` you no longer need to use WSL, you can use native Windows if you like. The installation is the same as on any other OS, i.e., 
```
pip install tfc
```
